INSERT INTO tb_campeonato (campeonato) VALUES ('Baiano');
INSERT INTO tb_campeonato (campeonato) VALUES ('Carioca');
INSERT INTO tb_campeonato (campeonato) VALUES ('Catarinense');
INSERT INTO tb_campeonato (campeonato) VALUES ('Cearense');
INSERT INTO tb_campeonato (campeonato) VALUES ('Gaúcho');
INSERT INTO tb_campeonato (campeonato) VALUES ('Goiano');
INSERT INTO tb_campeonato (campeonato) VALUES ('Mineiro');
INSERT INTO tb_campeonato (campeonato) VALUES ('Nordeste');
INSERT INTO tb_campeonato (campeonato) VALUES ('Paranaense');
INSERT INTO tb_campeonato (campeonato) VALUES ('Paulista');
INSERT INTO tb_campeonato (campeonato) VALUES ('Pernambucano');


INSERT INTO tb_clube (clube) VALUES ('Atlético Mineiro');
INSERT INTO tb_clube (clube) VALUES ('Avaí');
INSERT INTO tb_clube (clube) VALUES ('Bahia');
INSERT INTO tb_clube (clube) VALUES ('Botafogo (SP)');
INSERT INTO tb_clube (clube) VALUES ('Corinthians');
INSERT INTO tb_clube (clube) VALUES ('Coritiba');
INSERT INTO tb_clube (clube) VALUES ('CRB');
INSERT INTO tb_clube (clube) VALUES ('CSA');
INSERT INTO tb_clube (clube) VALUES ('Cruzeiro');
INSERT INTO tb_clube (clube) VALUES ('Figueirense');
INSERT INTO tb_clube (clube) VALUES ('Flamengo');
INSERT INTO tb_clube (clube) VALUES ('Fluminense');
INSERT INTO tb_clube (clube) VALUES ('Grêmio');
INSERT INTO tb_clube (clube) VALUES ('Guarani');
INSERT INTO tb_clube (clube) VALUES ('Internacional');
INSERT INTO tb_clube (clube) VALUES ('Ituano');
INSERT INTO tb_clube (clube) VALUES ('Londrina');
INSERT INTO tb_clube (clube) VALUES ('Náutico');
INSERT INTO tb_clube (clube) VALUES ('Palmeiras');
INSERT INTO tb_clube (clube) VALUES ('Ponte Preta');
INSERT INTO tb_clube (clube) VALUES ('Paysandu');
INSERT INTO tb_clube (clube) VALUES ('Remo');
INSERT INTO tb_clube (clube) VALUES ('Santa Cruz');
INSERT INTO tb_clube (clube) VALUES ('Sampaio Corrêa');
INSERT INTO tb_clube (clube) VALUES ('Santos');
INSERT INTO tb_clube (clube) VALUES ('São Paulo');
INSERT INTO tb_clube (clube) VALUES ('Sport Recife');
INSERT INTO tb_clube (clube) VALUES ('Tombense');
INSERT INTO tb_clube (clube) VALUES ('Vasco da Gama');
INSERT INTO tb_clube (clube) VALUES ('Vitória');
INSERT INTO tb_clube (clube) VALUES ('Ypiranga');


INSERT INTO tb_estadio (estadio) VALUES ('Aflitos');
INSERT INTO tb_estadio (estadio) VALUES ('Almeidão');
INSERT INTO tb_estadio (estadio) VALUES ('Allianz Parque');
INSERT INTO tb_estadio (estadio) VALUES ('Arena do Grêmio');
INSERT INTO tb_estadio (estadio) VALUES ('Arruda');
INSERT INTO tb_estadio (estadio) VALUES ('Baenão');
INSERT INTO tb_estadio (estadio) VALUES ('Barradão');
INSERT INTO tb_estadio (estadio) VALUES ('Beira-Rio');
INSERT INTO tb_estadio (estadio) VALUES ('Brinco de Ouro');
INSERT INTO tb_estadio (estadio) VALUES ('Castelão');
INSERT INTO tb_estadio (estadio) VALUES ('Colosso da Lagoa');
INSERT INTO tb_estadio (estadio) VALUES ('Couto Pereira');
INSERT INTO tb_estadio (estadio) VALUES ('Curuzu');
INSERT INTO tb_estadio (estadio) VALUES ('Estádio do Café');
INSERT INTO tb_estadio (estadio) VALUES ('Fonte Nova');
INSERT INTO tb_estadio (estadio) VALUES ('Ilha do Retiro');
INSERT INTO tb_estadio (estadio) VALUES ('Maracanã');
INSERT INTO tb_estadio (estadio) VALUES ('Mineirão');
INSERT INTO tb_estadio (estadio) VALUES ('Moisés Lucarelli');
INSERT INTO tb_estadio (estadio) VALUES ('Morumbi');
INSERT INTO tb_estadio (estadio) VALUES ('Neo Química Arena');
INSERT INTO tb_estadio (estadio) VALUES ('Novelli Júnior');
INSERT INTO tb_estadio (estadio) VALUES ('Orlando Scarpelli');
INSERT INTO tb_estadio (estadio) VALUES ('Rei Pelé');
INSERT INTO tb_estadio (estadio) VALUES ('Rei Pelé');
INSERT INTO tb_estadio (estadio) VALUES ('Ressacada');
INSERT INTO tb_estadio (estadio) VALUES ('Santa Cruz');


INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (7, 24, 13, 5, TIMESTAMP WITH TIME ZONE '2023-09-05T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (3, 10, 30, 11, TIMESTAMP WITH TIME ZONE '2023-04-12T16:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (11, 19, 8, 18, TIMESTAMP WITH TIME ZONE '2023-11-28T20:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (5, 27, 4, 26, TIMESTAMP WITH TIME ZONE '2023-07-15T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (2, 13, 15, 7, TIMESTAMP WITH TIME ZONE '2023-02-23T16:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (9, 6, 29, 9, TIMESTAMP WITH TIME ZONE '2023-10-08T20:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (4, 14, 12, 3, TIMESTAMP WITH TIME ZONE '2023-06-01T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (10, 22, 10, 17, TIMESTAMP WITH TIME ZONE '2023-11-11T16:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (1, 3, 1, 21, TIMESTAMP WITH TIME ZONE '2023-01-18T20:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (8, 16, 20, 31, TIMESTAMP WITH TIME ZONE '2023-09-29T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (6, 21, 19, 2, TIMESTAMP WITH TIME ZONE '2023-08-03T16:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (3, 8, 25, 6, TIMESTAMP WITH TIME ZONE '2023-05-19T20:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (10, 1, 16, 30, TIMESTAMP WITH TIME ZONE '2023-11-08T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (2, 7, 14, 24, TIMESTAMP WITH TIME ZONE '2023-03-27T16:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (9, 5, 3, 20, TIMESTAMP WITH TIME ZONE '2023-10-12T20:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (1, 17, 9, 28, TIMESTAMP WITH TIME ZONE '2023-01-04T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (8, 12, 22, 1, TIMESTAMP WITH TIME ZONE '2023-09-14T16:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (4, 11, 26, 13, TIMESTAMP WITH TIME ZONE '2023-06-09T10:00:00Z');
INSERT INTO tb_Organiza_Campeonato (id_Campeonato, id_Estadio, id_Time_Casa, id_Time_Visitante, data_Hora) VALUES (5, 2, 4, 27, TIMESTAMP WITH TIME ZONE '2023-07-23T16:00:00Z');
